apiVersion: v1
kind: Service
metadata:
  name: chatbot-app-service
  namespace: chatbot-monitoring
spec:
  type: NodePort
  selector:
    app: chatbot-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000