apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  namespace: chatbot-monitoring
data:
  config.yaml: |
    auth_enabled: false
    server:
      http_listen_port: 3100
      grpc_listen_port: 9096
    ingester:
      lifecycler:
        address: 127.0.0.1
        ring:
          kvstore:
            store: inmemory
          replication_factor: 1
        final_sleep: 0s
      chunk_idle_period: 5m
      max_chunk_age: 1h
      chunk_target_size: 1048576
      chunk_retain_period: 30s
      max_transfer_retries: 0
      wal:
        enabled: true
        dir: /loki/data/wal
    compactor: # <-- Adicione esta seção
      working_directory: /loki/data/compactor
      shared_store: filesystem
    schema_config:
      configs:
        - from: 2020-10-24
          store: boltdb-shipper
          object_store: filesystem
          schema: v11
          index:
            prefix: index_
            period: 24h
    storage_config:
      boltdb_shipper:
        active_index_directory: /loki/data/index
        cache_location: /loki/data/cache
        shared_store: filesystem
      filesystem:
        directory: /loki/data/chunks
    limits_config:
      ingestion_rate_mb: 4
      ingestion_burst_size_mb: 6
      max_concurrent_tail_requests: 20