apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: chatbot-monitoring
spec:
  selector:
    app: loki
  ports:
    - protocol: TCP
      port: 3100
      targetPort: http-metrics
      name: http-metrics