apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: chatbot-monitoring
spec:
  selector:
    app: chatbot
  ports:
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
      protocol: TCP
    - name: otlp-http
      port: 4318
      targetPort: 4318
      protocol: TCP
  type: ClusterIP
