apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-config
  namespace: chatbot-monitoring
data:
  otel-collector-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:

    processors:
      batch:
        timeout: 10s

    exporters:
      loki:
        endpoint: "http://loki:3100/loki/api/v1/push"
      # Este exportador expõe as métricas em um endpoint para o Prometheus
      # poder extraí-las.
      prometheus:
        endpoint: "0.0.0.0:8889"
        send_timestamps: true
      otlp/tempo:
        endpoint: "tempo.chatbot-monitoring.svc.cluster.local:4317"
        tls:
          insecure: true

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp/tempo]
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [prometheus] # Pipeline agora usa o exportador prometheus
        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [loki]
