apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-config
  namespace: chatbot-monitoring
data:
  otel-collector-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318

    processors:
      batch: {}

    exporters:
      # Exporter para o Loki (Logs)
      loki:
        endpoint: http://loki:3100/loki/api/v1/push
      
      # Exporter para o Prometheus (Métricas)
      prometheus:
        endpoint: "0.0.0.0:8889"

      # Exporter para o Tempo (Traces)
      otlp:
        endpoint: tempo:9095
        
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp]
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [prometheus]
        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [loki]