apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: chatbot-monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'loki'
        static_configs:
          - targets: ['loki.chatbot-monitoring.svc.cluster.local:3100']

      - job_name: 'tempo'
        static_configs:
          - targets: ['tempo.chatbot-monitoring.svc.cluster.local:3100']

    # New section for accepting metrics from the OpenTelemetry Collector
    remote_write:
      - url: http://localhost:9090/api/v1/write
