apiVersion: v1
kind: Service
metadata:
  name: grafana-lb
  namespace: chatbot-monitoring
spec:
  type: NodePort
  selector:
    app: grafana
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      nodePort: 32100  # Porta ajustada
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-lb
  namespace: chatbot-monitoring
spec:
  type: NodePort
  selector:
    app: prometheus
  ports:
    - name: http
      port: 9090
      targetPort: 9090
      nodePort: 32101  # Porta ajustada
---
apiVersion: v1
kind: Service
metadata:
  name: loki-lb
  namespace: chatbot-monitoring
spec:
  type: NodePort
  selector:
    app: loki
  ports:
    - name: http
      port: 3100
      targetPort: 3100
      nodePort: 32102  # Porta ajustada
---
apiVersion: v1
kind: Service
metadata:
  name: tempo-lb
  namespace: chatbot-monitoring
spec:
  type: NodePort
  selector:
    app: tempo
  ports:
    - name: http
      port: 3200
      targetPort: 3200
      nodePort: 32103  # Porta ajustada
---
apiVersion: v1
kind: Service
metadata:
  name: otel-collector-lb
  namespace: chatbot-monitoring
spec:
  type: NodePort
  selector:
    app: otel-collector
  ports:
    - name: grpc
      port: 4317
      targetPort: 4317
      nodePort: 32104  # Porta ajustada
    - name: http
      port: 4318
      targetPort: 4318
      nodePort: 32105  # Porta ajustada
