apiVersion: v1
kind: Service
metadata:
  name: tempo
  namespace: chatbot-monitoring
spec:
  type: ClusterIP
  selector:
    app: tempo
  ports:
    - name: http
      port: 3200
      targetPort: 3200
    - name: grpc
      port: 9095
      targetPort: 9095