apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-config
  namespace: chatbot-monitoring
data:
  tempo-local.yaml: |
    server:
      http_listen_port: 3200
      grpc_listen_port: 9095

    distributor:
      receivers:
        otlp:
          protocols:
            grpc:
            http:

    ingester:
      max_block_duration: 5m

    storage:
      trace:
        backend: local
        local:
          path: /var/tempo/traces